### ISSUE TITLE
[PE-D][Tester C] Incr does not guard against multiple identifier inputs

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W09-1/tp#171]
![image.png](https://raw.githubusercontent.com/shauneang/ped/main/files/ca8b8427-2949-4e17-911f-4aa8a55ca9cc.png)

![image.png](https://raw.githubusercontent.com/shauneang/ped/main/files/9718c63c-509c-4381-a4f3-a33b68ea5269.png)

using the phone number and email from two different persons should throw and error but instead, the first person is edited

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: shauneang/ped#2

**Comment by Samsation** [comment]
Thank you for the bug report 🐱 

We have properly handled the case for multiple prefixes

Fixed in PR #205
