### ISSUE TITLE
[PE-D][Tester B] Editing a person with a reward value over 2147483647

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W09-1/tp#173]
![Issue1.png](https://raw.githubusercontent.com/e1010101/ped/main/files/b48d1b50-6103-4866-9342-298bd1595f6c.png)

The error message is incorrect. The value is non-negative and not blank, but the app still displays an error.

-------------
Labels: `type.FunctionalityBug` `severity.Low`
original: e1010101/ped#1

**Comment by Samsation** [comment]
Thank you for the bug report 🐱 

We have properly handled the case for MAX_INTEGER values

Fixed in PR #205
