### ISSUE TITLE
[PE-D][Tester D] incr command: Large input results in error not describing the problem

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W09-1/tp#179]
Input: `incr 999999999999999999999 p/22224444`

Expected output: Error message indicating that the input value is too large.

Actual output: Error message that indicates `Invalid command format!` and no mention of large input.

![image.png](https://raw.githubusercontent.com/sohenze/ped/main/files/ff4fd294-0ec4-434e-94e2-bfbf3cd7cca0.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: sohenze/ped#3

**Comment by Samsation** [comment]
Thank you for the bug report 🐱 

We have included a more specific error message for the corresponding input

Fixed in PR #205
